# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kala185/Desktop/libkrf

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kala185/Desktop/libkrf

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kala185/Desktop/libkrf/CMakeFiles /home/kala185/Desktop/libkrf//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kala185/Desktop/libkrf/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libkrf

# Build rule for target.
libkrf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libkrf
.PHONY : libkrf

# fast build rule for target.
libkrf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libkrf.dir/build.make CMakeFiles/libkrf.dir/build
.PHONY : libkrf/fast

#=============================================================================
# Target rules for targets named basic_capture

# Build rule for target.
basic_capture: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 basic_capture
.PHONY : basic_capture

# fast build rule for target.
basic_capture/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basic_capture.dir/build.make CMakeFiles/basic_capture.dir/build
.PHONY : basic_capture/fast

examples/basic_capture.o: examples/basic_capture.cpp.o
.PHONY : examples/basic_capture.o

# target to build an object file
examples/basic_capture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basic_capture.dir/build.make CMakeFiles/basic_capture.dir/examples/basic_capture.cpp.o
.PHONY : examples/basic_capture.cpp.o

examples/basic_capture.i: examples/basic_capture.cpp.i
.PHONY : examples/basic_capture.i

# target to preprocess a source file
examples/basic_capture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basic_capture.dir/build.make CMakeFiles/basic_capture.dir/examples/basic_capture.cpp.i
.PHONY : examples/basic_capture.cpp.i

examples/basic_capture.s: examples/basic_capture.cpp.s
.PHONY : examples/basic_capture.s

# target to generate assembly for a file
examples/basic_capture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basic_capture.dir/build.make CMakeFiles/basic_capture.dir/examples/basic_capture.cpp.s
.PHONY : examples/basic_capture.cpp.s

src/analysis.o: src/analysis.cpp.o
.PHONY : src/analysis.o

# target to build an object file
src/analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libkrf.dir/build.make CMakeFiles/libkrf.dir/src/analysis.cpp.o
.PHONY : src/analysis.cpp.o

src/analysis.i: src/analysis.cpp.i
.PHONY : src/analysis.i

# target to preprocess a source file
src/analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libkrf.dir/build.make CMakeFiles/libkrf.dir/src/analysis.cpp.i
.PHONY : src/analysis.cpp.i

src/analysis.s: src/analysis.cpp.s
.PHONY : src/analysis.s

# target to generate assembly for a file
src/analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libkrf.dir/build.make CMakeFiles/libkrf.dir/src/analysis.cpp.s
.PHONY : src/analysis.cpp.s

src/capture.o: src/capture.cpp.o
.PHONY : src/capture.o

# target to build an object file
src/capture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libkrf.dir/build.make CMakeFiles/libkrf.dir/src/capture.cpp.o
.PHONY : src/capture.cpp.o

src/capture.i: src/capture.cpp.i
.PHONY : src/capture.i

# target to preprocess a source file
src/capture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libkrf.dir/build.make CMakeFiles/libkrf.dir/src/capture.cpp.i
.PHONY : src/capture.cpp.i

src/capture.s: src/capture.cpp.s
.PHONY : src/capture.s

# target to generate assembly for a file
src/capture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libkrf.dir/build.make CMakeFiles/libkrf.dir/src/capture.cpp.s
.PHONY : src/capture.cpp.s

src/monitor.o: src/monitor.cpp.o
.PHONY : src/monitor.o

# target to build an object file
src/monitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libkrf.dir/build.make CMakeFiles/libkrf.dir/src/monitor.cpp.o
.PHONY : src/monitor.cpp.o

src/monitor.i: src/monitor.cpp.i
.PHONY : src/monitor.i

# target to preprocess a source file
src/monitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libkrf.dir/build.make CMakeFiles/libkrf.dir/src/monitor.cpp.i
.PHONY : src/monitor.cpp.i

src/monitor.s: src/monitor.cpp.s
.PHONY : src/monitor.s

# target to generate assembly for a file
src/monitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libkrf.dir/build.make CMakeFiles/libkrf.dir/src/monitor.cpp.s
.PHONY : src/monitor.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libkrf.dir/build.make CMakeFiles/libkrf.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libkrf.dir/build.make CMakeFiles/libkrf.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libkrf.dir/build.make CMakeFiles/libkrf.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... basic_capture"
	@echo "... libkrf"
	@echo "... examples/basic_capture.o"
	@echo "... examples/basic_capture.i"
	@echo "... examples/basic_capture.s"
	@echo "... src/analysis.o"
	@echo "... src/analysis.i"
	@echo "... src/analysis.s"
	@echo "... src/capture.o"
	@echo "... src/capture.i"
	@echo "... src/capture.s"
	@echo "... src/monitor.o"
	@echo "... src/monitor.i"
	@echo "... src/monitor.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

